# Generated by Django 5.1.6 on 2025-02-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('start_date', models.DateField(default=None, verbose_name='Дата начала курса')),
                ('end_date', models.DateField(default=None, verbose_name='Дата окончания курса')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='Логотип курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('text', models.TextField(verbose_name='Текст урока')),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='cours.cours', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_review', to='cours.cours', verbose_name='Ревью')),
            ],
            options={
                'verbose_name': 'ревью',
                'verbose_name_plural': 'Ревью',
            },
        ),
    ]
